# Change these first
owner: usernameok # Your GitHub organization or username, where this repository lives
repo: dome-uptime # The name of this repository

sites:
  - name: dome
    url: https://dome-1.onrender.com/
    port: 80
    check: "tcp-ping"
    ipv6: true

